package com.Id.crawler.model;

public class Profile {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile.id
     *
     * @mbggenerated Mon Apr 02 23:18:29 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile.open_id
     *
     * @mbggenerated Mon Apr 02 23:18:29 CST 2018
     */
    private String openId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile.profile_name
     *
     * @mbggenerated Mon Apr 02 23:18:29 CST 2018
     */
    private String profileName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile.password
     *
     * @mbggenerated Mon Apr 02 23:18:29 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile.email
     *
     * @mbggenerated Mon Apr 02 23:18:29 CST 2018
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile.address
     *
     * @mbggenerated Mon Apr 02 23:18:29 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column profile.phone
     *
     * @mbggenerated Mon Apr 02 23:18:29 CST 2018
     */
    private String phone;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile.id
     *
     * @return the value of profile.id
     *
     * @mbggenerated Mon Apr 02 23:18:29 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile.id
     *
     * @param id the value for profile.id
     *
     * @mbggenerated Mon Apr 02 23:18:29 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile.open_id
     *
     * @return the value of profile.open_id
     *
     * @mbggenerated Mon Apr 02 23:18:29 CST 2018
     */
    public String getOpenId() {
        return openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile.open_id
     *
     * @param openId the value for profile.open_id
     *
     * @mbggenerated Mon Apr 02 23:18:29 CST 2018
     */
    public void setOpenId(String openId) {
        this.openId = openId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile.profile_name
     *
     * @return the value of profile.profile_name
     *
     * @mbggenerated Mon Apr 02 23:18:29 CST 2018
     */
    public String getProfileName() {
        return profileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile.profile_name
     *
     * @param profileName the value for profile.profile_name
     *
     * @mbggenerated Mon Apr 02 23:18:29 CST 2018
     */
    public void setProfileName(String profileName) {
        this.profileName = profileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile.password
     *
     * @return the value of profile.password
     *
     * @mbggenerated Mon Apr 02 23:18:29 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile.password
     *
     * @param password the value for profile.password
     *
     * @mbggenerated Mon Apr 02 23:18:29 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile.email
     *
     * @return the value of profile.email
     *
     * @mbggenerated Mon Apr 02 23:18:29 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile.email
     *
     * @param email the value for profile.email
     *
     * @mbggenerated Mon Apr 02 23:18:29 CST 2018
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile.address
     *
     * @return the value of profile.address
     *
     * @mbggenerated Mon Apr 02 23:18:29 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile.address
     *
     * @param address the value for profile.address
     *
     * @mbggenerated Mon Apr 02 23:18:29 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column profile.phone
     *
     * @return the value of profile.phone
     *
     * @mbggenerated Mon Apr 02 23:18:29 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column profile.phone
     *
     * @param phone the value for profile.phone
     *
     * @mbggenerated Mon Apr 02 23:18:29 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }
}